stages:
  install:
    cmd: pip3 install -r requirements.txt
  train:
    cmd: python3 train.py
    deps:
      - data/dataset.csv
      - train.py
    outs:
      - model.pkl
    metrics:
      - metrics.txt
#Just a comment
